# Generated by Django 4.2.21 on 2025-05-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='action_type',
            field=models.CharField(choices=[('decrease', 'Decrease'), ('increase', 'Increase')], default='increase', max_length=20),
            preserve_default=False,
        ),
    ]
