# Generated by Django 4.2.21 on 2025-05-16 15:21

from django.db import migrations, models
import transactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transactionlog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='amount',
            field=models.BigIntegerField(validators=[transactions.models.validate_positive]),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['seller', 'created_at'], name='transaction_seller__767833_idx'),
        ),
    ]
