# Generated by Django 4.2.21 on 2025-05-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='credit',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
